
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Id = 2F,
    MSSubClass = 20F,
    LotFrontage = 800F,
    LotArea = 9600F,
    OverallQual = 6F,
    OverallCond = 8F,
    YearBuilt = 1976F,
    YearRemodAdd = 1976F,
    MasVnrArea = 0F,
    BsmtFinSF1 = 978F,
    BsmtFinSF2 = 0F,
    BsmtUnfSF = 284F,
    TotalBsmtSF = 1262F,
    _1stFlrSF = 1262F,
    _2ndFlrSF = 0F,
    LowQualFinSF = 0F,
    GrLivArea = 1262F,
    BsmtFullBath = 0F,
    BsmtHalfBath = 1F,
    FullBath = 2F,
    HalfBath = 0F,
    BedroomAbvGr = 3F,
    KitchenAbvGr = 1F,
    TotRmsAbvGrd = 6F,
    Fireplaces = 1F,
    GarageYrBlt = 19760F,
    GarageCars = 2F,
    GarageArea = 460F,
    WoodDeckSF = 298F,
    OpenPorchSF = 0F,
    EnclosedPorch = 0F,
    _3SsnPorch = 0F,
    ScreenPorch = 0F,
    PoolArea = 0F,
    MiscVal = 0F,
    MoSold = 5F,
    YrSold = 2007F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual SalePrice with predicted SalePrice from sample data...\n\n");


Console.WriteLine($"Id: {2F}");
Console.WriteLine($"MSSubClass: {20F}");
Console.WriteLine($"LotFrontage: {800F}");
Console.WriteLine($"LotArea: {9600F}");
Console.WriteLine($"OverallQual: {6F}");
Console.WriteLine($"OverallCond: {8F}");
Console.WriteLine($"YearBuilt: {1976F}");
Console.WriteLine($"YearRemodAdd: {1976F}");
Console.WriteLine($"MasVnrArea: {0F}");
Console.WriteLine($"BsmtFinSF1: {978F}");
Console.WriteLine($"BsmtFinSF2: {0F}");
Console.WriteLine($"BsmtUnfSF: {284F}");
Console.WriteLine($"TotalBsmtSF: {1262F}");
Console.WriteLine($"_1stFlrSF: {1262F}");
Console.WriteLine($"_2ndFlrSF: {0F}");
Console.WriteLine($"LowQualFinSF: {0F}");
Console.WriteLine($"GrLivArea: {1262F}");
Console.WriteLine($"BsmtFullBath: {0F}");
Console.WriteLine($"BsmtHalfBath: {1F}");
Console.WriteLine($"FullBath: {2F}");
Console.WriteLine($"HalfBath: {0F}");
Console.WriteLine($"BedroomAbvGr: {3F}");
Console.WriteLine($"KitchenAbvGr: {1F}");
Console.WriteLine($"TotRmsAbvGrd: {6F}");
Console.WriteLine($"Fireplaces: {1F}");
Console.WriteLine($"GarageYrBlt: {19760F}");
Console.WriteLine($"GarageCars: {2F}");
Console.WriteLine($"GarageArea: {460F}");
Console.WriteLine($"WoodDeckSF: {298F}");
Console.WriteLine($"OpenPorchSF: {0F}");
Console.WriteLine($"EnclosedPorch: {0F}");
Console.WriteLine($"_3SsnPorch: {0F}");
Console.WriteLine($"ScreenPorch: {0F}");
Console.WriteLine($"PoolArea: {0F}");
Console.WriteLine($"MiscVal: {0F}");
Console.WriteLine($"MoSold: {5F}");
Console.WriteLine($"YrSold: {2007F}");
Console.WriteLine($"SalePrice: {181500F}");


// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted SalePrice: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

