// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class MLModel1
{
    /// <summary>
    /// model input class for MLModel1.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(0)]
        [ColumnName(@"Id")]
        public float Id { get; set; }

        [LoadColumn(1)]
        [ColumnName(@"MSSubClass")]
        public float MSSubClass { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"LotFrontage")]
        public float LotFrontage { get; set; }

        [LoadColumn(3)]
        [ColumnName(@"LotArea")]
        public float LotArea { get; set; }

        [LoadColumn(4)]
        [ColumnName(@"OverallQual")]
        public float OverallQual { get; set; }

        [LoadColumn(5)]
        [ColumnName(@"OverallCond")]
        public float OverallCond { get; set; }

        [LoadColumn(6)]
        [ColumnName(@"YearBuilt")]
        public float YearBuilt { get; set; }

        [LoadColumn(7)]
        [ColumnName(@"YearRemodAdd")]
        public float YearRemodAdd { get; set; }

        [LoadColumn(8)]
        [ColumnName(@"MasVnrArea")]
        public float MasVnrArea { get; set; }

        [LoadColumn(9)]
        [ColumnName(@"BsmtFinSF1")]
        public float BsmtFinSF1 { get; set; }

        [LoadColumn(10)]
        [ColumnName(@"BsmtFinSF2")]
        public float BsmtFinSF2 { get; set; }

        [LoadColumn(11)]
        [ColumnName(@"BsmtUnfSF")]
        public float BsmtUnfSF { get; set; }

        [LoadColumn(12)]
        [ColumnName(@"TotalBsmtSF")]
        public float TotalBsmtSF { get; set; }

        [LoadColumn(13)]
        [ColumnName(@"1stFlrSF")]
        public float _1stFlrSF { get; set; }

        [LoadColumn(14)]
        [ColumnName(@"2ndFlrSF")]
        public float _2ndFlrSF { get; set; }

        [LoadColumn(15)]
        [ColumnName(@"LowQualFinSF")]
        public float LowQualFinSF { get; set; }

        [LoadColumn(16)]
        [ColumnName(@"GrLivArea")]
        public float GrLivArea { get; set; }

        [LoadColumn(17)]
        [ColumnName(@"BsmtFullBath")]
        public float BsmtFullBath { get; set; }

        [LoadColumn(18)]
        [ColumnName(@"BsmtHalfBath")]
        public float BsmtHalfBath { get; set; }

        [LoadColumn(19)]
        [ColumnName(@"FullBath")]
        public float FullBath { get; set; }

        [LoadColumn(20)]
        [ColumnName(@"HalfBath")]
        public float HalfBath { get; set; }

        [LoadColumn(21)]
        [ColumnName(@"BedroomAbvGr")]
        public float BedroomAbvGr { get; set; }

        [LoadColumn(22)]
        [ColumnName(@"KitchenAbvGr")]
        public float KitchenAbvGr { get; set; }

        [LoadColumn(23)]
        [ColumnName(@"TotRmsAbvGrd")]
        public float TotRmsAbvGrd { get; set; }

        [LoadColumn(24)]
        [ColumnName(@"Fireplaces")]
        public float Fireplaces { get; set; }

        [LoadColumn(25)]
        [ColumnName(@"GarageYrBlt")]
        public float GarageYrBlt { get; set; }

        [LoadColumn(26)]
        [ColumnName(@"GarageCars")]
        public float GarageCars { get; set; }

        [LoadColumn(27)]
        [ColumnName(@"GarageArea")]
        public float GarageArea { get; set; }

        [LoadColumn(28)]
        [ColumnName(@"WoodDeckSF")]
        public float WoodDeckSF { get; set; }

        [LoadColumn(29)]
        [ColumnName(@"OpenPorchSF")]
        public float OpenPorchSF { get; set; }

        [LoadColumn(30)]
        [ColumnName(@"EnclosedPorch")]
        public float EnclosedPorch { get; set; }

        [LoadColumn(31)]
        [ColumnName(@"3SsnPorch")]
        public float _3SsnPorch { get; set; }

        [LoadColumn(32)]
        [ColumnName(@"ScreenPorch")]
        public float ScreenPorch { get; set; }

        [LoadColumn(33)]
        [ColumnName(@"PoolArea")]
        public float PoolArea { get; set; }

        [LoadColumn(34)]
        [ColumnName(@"MiscVal")]
        public float MiscVal { get; set; }

        [LoadColumn(35)]
        [ColumnName(@"MoSold")]
        public float MoSold { get; set; }

        [LoadColumn(36)]
        [ColumnName(@"YrSold")]
        public float YrSold { get; set; }

        [LoadColumn(37)]
        [ColumnName(@"SalePrice")]
        public float SalePrice { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for MLModel1.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"Id")]
        public float Id { get; set; }

        [ColumnName(@"MSSubClass")]
        public float MSSubClass { get; set; }

        [ColumnName(@"LotFrontage")]
        public float LotFrontage { get; set; }

        [ColumnName(@"LotArea")]
        public float LotArea { get; set; }

        [ColumnName(@"OverallQual")]
        public float OverallQual { get; set; }

        [ColumnName(@"OverallCond")]
        public float OverallCond { get; set; }

        [ColumnName(@"YearBuilt")]
        public float YearBuilt { get; set; }

        [ColumnName(@"YearRemodAdd")]
        public float YearRemodAdd { get; set; }

        [ColumnName(@"MasVnrArea")]
        public float MasVnrArea { get; set; }

        [ColumnName(@"BsmtFinSF1")]
        public float BsmtFinSF1 { get; set; }

        [ColumnName(@"BsmtFinSF2")]
        public float BsmtFinSF2 { get; set; }

        [ColumnName(@"BsmtUnfSF")]
        public float BsmtUnfSF { get; set; }

        [ColumnName(@"TotalBsmtSF")]
        public float TotalBsmtSF { get; set; }

        [ColumnName(@"1stFlrSF")]
        public float _1stFlrSF { get; set; }

        [ColumnName(@"2ndFlrSF")]
        public float _2ndFlrSF { get; set; }

        [ColumnName(@"LowQualFinSF")]
        public float LowQualFinSF { get; set; }

        [ColumnName(@"GrLivArea")]
        public float GrLivArea { get; set; }

        [ColumnName(@"BsmtFullBath")]
        public float BsmtFullBath { get; set; }

        [ColumnName(@"BsmtHalfBath")]
        public float BsmtHalfBath { get; set; }

        [ColumnName(@"FullBath")]
        public float FullBath { get; set; }

        [ColumnName(@"HalfBath")]
        public float HalfBath { get; set; }

        [ColumnName(@"BedroomAbvGr")]
        public float BedroomAbvGr { get; set; }

        [ColumnName(@"KitchenAbvGr")]
        public float KitchenAbvGr { get; set; }

        [ColumnName(@"TotRmsAbvGrd")]
        public float TotRmsAbvGrd { get; set; }

        [ColumnName(@"Fireplaces")]
        public float Fireplaces { get; set; }

        [ColumnName(@"GarageYrBlt")]
        public float GarageYrBlt { get; set; }

        [ColumnName(@"GarageCars")]
        public float GarageCars { get; set; }

        [ColumnName(@"GarageArea")]
        public float GarageArea { get; set; }

        [ColumnName(@"WoodDeckSF")]
        public float WoodDeckSF { get; set; }

        [ColumnName(@"OpenPorchSF")]
        public float OpenPorchSF { get; set; }

        [ColumnName(@"EnclosedPorch")]
        public float EnclosedPorch { get; set; }

        [ColumnName(@"3SsnPorch")]
        public float _3SsnPorch { get; set; }

        [ColumnName(@"ScreenPorch")]
        public float ScreenPorch { get; set; }

        [ColumnName(@"PoolArea")]
        public float PoolArea { get; set; }

        [ColumnName(@"MiscVal")]
        public float MiscVal { get; set; }

        [ColumnName(@"MoSold")]
        public float MoSold { get; set; }

        [ColumnName(@"YrSold")]
        public float YrSold { get; set; }

        [ColumnName(@"SalePrice")]
        public float SalePrice { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }
}
